import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/About.module.css'
import data from '../data/education.json'
import { useState } from 'react'
import Card from '../components/Card'

const inter = Inter({ subsets: ['latin'] })

export default function About() {

  console.log(data);
  const [information, setInformation] = useState([...data])

  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div>
          <div className={styles.heading}>Student Information:</div>
          {
            information && information.map((info, index) => {
              if(info.firstName === "Alhaitham") {
              return(
                <Card key={index} degree={info.studentNumber} colour="transparent" font="36px"/>
              )
              }
            })
          }
          {
            information && information.map((info, index) => {
              if(info.firstName === "Alhaitham") {
              return(
                <Card key={index} degree={info.firstName} colour="none" font="30px"/>
              )
              }
            })
          }
          {
            information && information.map((info, index) => {
              if(info.firstName === "Alhaitham") {
              return(
                <Card key={index} degree={info.gpa} colour="none" font="30px"/>
              )
              }
            })
          }
           {
            information && information.map((info, index) => {
              if(info.firstName === "Wanderer") {
              return(
                <Card key={index} degree={info.studentNumber} colour="transparent" font="36px"/>
              )
              }
            })
          }
          {
            information && information.map((info, index) => {
              if(info.firstName === "Wanderer") {
              return(
                <Card key={index} degree={info.firstName} colour="none" font="30px"/>
              )
              }
            })
          }
          {
            information && information.map((info, index) => {
              if(info.firstName === "Wanderer") {
              return(
                <Card key={index} degree={info.gpa} colour="none" font="30px"/>
              )
              }
            })
          }
          {
            information && information.map((info, index) => {
              if(info.firstName === "Xiao") {
              return(
                <Card key={index} degree={info.studentNumber} colour="transparent" font="36px" />
              )
              }
            })
          }
          
           {
            information && information.map((info, index) => {
              if(info.firstName === "Xiao") {
              return(
                <Card key={index} degree={info.firstName} colour="none" font="30px"/>
              )
              }
            })
          }
          {
            information && information.map((info, index) => {
              if(info.firstName === "Xiao") {
              return(
                <Card key={index} degree={info.gpa} colour="none" font="30px"/>
              )
              }
            })
          }
        </div>
      </main>
    </>
  )
}

